### ISSUE TITLE
Actions Runner - Code/Features Cleanup

### ISSUE THREAD

**Issue by juliobbv** [actions/runner#121]
Created this issue to keep track of the code/features that are no longer needed.

Please keep the below list updated with desc of features that has to be removed along with their status.

- [x] Unused authentication methods
    - `Integrated`, `Negotiate`, `Alternate`, `ServiceIdentity` #123 
    - `PAT`, `AAD` #218
- [x] `AsyncCommandContext` #124
- [x] Comment/code references (not server references) still pointing to the 'AZP agent' #125, #227, #228
- [x] Capabilities support
    - #130 did most of the cleanup already, #197 to clean rest of non-SDK code
    - Added check in server list to clean up SDK code (contracts, etc...)
- [x] LocalRun #218
- [x] SDK code
    - Build2 SDK #219
    - DT Expression V1 #218
    - DT Pipeline contract for orchestration (Phase, Job, Pipeline, etc) #218
    - DT WebApi legacy contract (Task, DeploymentGroup, etc) #218
    - VSS WebApis #218, #222
    - TFS common #218, #222 
- [x] "PII" variables in job message scrubbing #209
- [x] Unused Constants in Common.Constants #197
- [x] Legacy Proxy code #206
- [x] Configuration Store `agentId`
    - Should we rename it to `runnerId`, and keep `agentId` for back-compat? (not going to do rename)
- [x] Re-enable/delete commented-out test code
    - AgentL0.cs #209
    - ActionManagerL0.cs #214
    - JobExtensionL0.cs #214
    - JobRunnerL0.cs #214
    - StepsRunnerL0.cs #214
    - TaskCommandExtensionL0.cs #214
    - ProcessInvokerL0.cs #214

Untied to open-sourcing runner:
- Build2 (v1) Artifact publish/download #212
